CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_SPI=y
CONFIG_PWM=y

CONFIG_LIB_FXLS89XX=y

# Flash storage
CONFIG_FLASH=y
CONFIG_NVS=y

# MCUMGR
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_CRC=y
CONFIG_MCUMGR=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_CONN_PARAM_CONTROL=y

# Enable the Shell mcumgr transport.
# CONFIG_BASE64=y
# CONFIG_CRC=y
# CONFIG_SHELL=y
# CONFIG_SHELL_BACKEND_SERIAL=y
# CONFIG_MCUMGR_TRANSPORT_SHELL=y

# Enable the mcumgr Packet Reassembly feature over Bluetooth and its configuration dependencies.
# MCUmgr buffer size is optimized to fit one SMP packet divided into five Bluetooth Write Commands,
# transmitted with the maximum possible MTU value: 498 bytes.
CONFIG_MCUMGR_TRANSPORT_BT_REASSEMBLY=y
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=2475
CONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=4608

# MCUBOOT
CONFIG_BOOTLOADER_MCUBOOT=y

# Enable most MCUMGR commands
CONFIG_STATS=y
CONFIG_STATS_NAMES=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_STAT=y
CONFIG_MCUMGR_GRP_ZBASIC=y
CONFIG_MCUMGR_GRP_ZBASIC_STORAGE_ERASE=y

# Disable shell commands that are not needed
CONFIG_CLOCK_CONTROL_NRF_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_FLASH_SHELL=n

# Enable BLE FOTA
CONFIG_BT_DFU_SMP=y
CONFIG_DFU_TARGET=y

CONFIG_LPED_FACTORY_RESET_AT_STARTUP=n
CONFIG_LPED_IGNORE_DOCK_AT_STARTUP=n
CONFIG_LPED_FORCE_CONNECTABLE_AT_STARTUP=n
CONFIG_LPED_CAP_STATE_IN_ROLLING_MSG=y
#CONFIG_LPED_CAP_STATE_INTERVAL=3
CONFIG_LPED_DOCK_DEBOUNCE_TIME=100
CONFIG_LPED_ACC_DEBOUNCE_TIME=100
CONFIG_LPED_VISIBILITY_TIMEOUT=60
CONFIG_LPED_CONNECTABLE_TIMEOUT=30
CONFIG_LPED_CONNECTED_TIMEOUT=600
CONFIG_LPED_DOCK_BUTTON_LONG_PRESS_DURATION=2
CONFIG_LPED_ACC_BOOT_DURATION=20
CONFIG_LPED_BT_STATE_INTERVAL=200

CONFIG_UART_CONSOLE=n

# ======= ENABLE FOR DEBUGGING ON DEMO DICE
# CONFIG_DEBUG=y

# CONFIG_LOG=y
# CONFIG_HW_STACK_PROTECTION=y

# # Set 32kHz source to be synthesized from high speed source
# CONFIG_CLOCK_CONTROL=y
# CONFIG_CLOCK_CONTROL_NRF=y
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_SYNTH=y

# # Enable RTT output
# CONFIG_CONSOLE=y
# CONFIG_RTT_CONSOLE=y
# # CONFIG_LOG_BACKEND_RTT=y
# CONFIG_USE_SEGGER_RTT=y
# CONFIG_SERIAL=y
# CONFIG_STDOUT_CONSOLE=y
# CONFIG_UART_CONSOLE=n
# CONFIG_SHELL_BACKEND_RTT=y

# # CONFIG_THREAD_ANALYZER=y
# # CONFIG_THREAD_ANALYZER_AUTO=y
# # CONFIG_STACK_SENTINEL=y
# # CONFIG_STACK_CANARIES=y
# # # =======

# # ======= ENABLE TO LIMIT MEMORY ON DEMO BOARD
# # CONFIG_SRAM_SIZE=24
# # CONFIG_FLASH_SIZE=192
# # =======

CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="LPEDv2"
CONFIG_BT_EXT_ADV=y

CONFIG_BT_BROADCASTER=y
CONFIG_BT_PERIPHERAL=y

CONFIG_BT_SMP=y

# memory size optimizations
CONFIG_I2C=n
CONFIG_WATCHDOG=n
CONFIG_SERIAL=n
CONFIG_DYNAMIC_INTERRUPTS=n
CONFIG_IRQ_OFFLOAD=n
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_CUSTOM_DATA=n
CONFIG_FPU=n
CONFIG_BT_CTLR_PRIVACY=n
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_DEBUG_NONE=y
CONFIG_BT_ASSERT=n
CONFIG_BT_DATA_LEN_UPDATE=n
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_GATT_CACHING=n
CONFIG_BT_GATT_SERVICE_CHANGED=n
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=n
CONFIG_BT_BUF_EVT_DISCARDABLE_COUNT=1
CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE=58
CONFIG_BT_BUF_EVT_RX_COUNT=2
CONFIG_BT_CONN_TX_MAX=3
CONFIG_BT_L2CAP_TX_BUF_COUNT=2
CONFIG_BT_BUF_ACL_TX_COUNT=3
CONFIG_BT_L2CAP_TX_MTU=498
CONFIG_BT_BUF_ACL_RX_SIZE=502
CONFIG_BT_BUF_ACL_TX_SIZE=502
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_RX_STACK_SIZE=1384
CONFIG_BT_HCI_TX_STACK_SIZE_WITH_PROMPT=y
CONFIG_BT_HCI_TX_STACK_SIZE=640
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2400
CONFIG_MAIN_STACK_SIZE=2400
CONFIG_IDLE_STACK_SIZE=128
CONFIG_ISR_STACK_SIZE=1024