CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_SPI=y
CONFIG_PWM=y

CONFIG_LIB_FXLS89XX=y

# Flash storage
CONFIG_FLASH=y
CONFIG_NVS=y

CONFIG_MCUMGR=y
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_CRC=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_OS_BOOTLOADER_INFO=y
CONFIG_MCUMGR_TRANSPORT_BT_REASSEMBLY=y
CONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=4608
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_DFU_TARGET=y
CONFIG_BT_DFU_SMP=y
CONFIG_MCUMGR_GRP_ZBASIC=y
CONFIG_MCUMGR_GRP_ZBASIC_STORAGE_ERASE=y
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=4608
CONFIG_BASE64=y
CONFIG_CRC=y
CONFIG_SHELL=y
CONFIG_MCUMGR_TRANSPORT_SHELL=y
CONFIG_MCUMGR_GRP_STAT=y
CONFIG_STATS_NAMES=y
CONFIG_STATS=y
CONFIG_MCUMGR_GRP_OS_TASKSTAT=y
CONFIG_THREAD_MONITOR=y

# Disable commands that are not needed
CONFIG_CLOCK_CONTROL_NRF_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_FLASH_SHELL=n

# LPED specific configs
CONFIG_LPED_FACTORY_RESET_AT_STARTUP=n
CONFIG_LPED_IGNORE_DOCK_AT_STARTUP=n
CONFIG_LPED_FORCE_CONNECTABLE_AT_STARTUP=n
CONFIG_LPED_CAP_STATE_IN_ROLLING_MSG=y
CONFIG_LPED_BT_STATE_INTERVAL=200
CONFIG_LPED_DEBUG_DISABLE_ACC=n
CONFIG_LPED_LED_EFFECTS_STACK_SIZE=2048
CONFIG_LPED_BOOT_ANIMATION=n
CONFIG_LPED_LED_FADE_TYPE_FAST_DURATION=100
CONFIG_LPED_RGB_LED_COMMON_ANODE=y

CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="LPEDv2"
CONFIG_BT_EXT_ADV=y

CONFIG_BT_BROADCASTER=y
CONFIG_BT_PERIPHERAL=y

CONFIG_BT_BAS=y

# memory size optimizations
CONFIG_I2C=n
CONFIG_WATCHDOG=n
CONFIG_SERIAL=n
CONFIG_DYNAMIC_INTERRUPTS=n
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_CUSTOM_DATA=n
CONFIG_FPU=n
CONFIG_BT_CTLR_PRIVACY=n
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_DEBUG_NONE=y
CONFIG_BT_ASSERT=n
CONFIG_BT_DATA_LEN_UPDATE=n
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_GATT_SERVICE_CHANGED=n
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=n
CONFIG_BT_BUF_EVT_DISCARDABLE_COUNT=1
CONFIG_BT_BUF_EVT_RX_COUNT=2
CONFIG_BT_L2CAP_TX_BUF_COUNT=2
CONFIG_BT_L2CAP_TX_MTU=498
CONFIG_BT_BUF_ACL_RX_SIZE=502
CONFIG_BT_BUF_ACL_TX_SIZE=502
CONFIG_BT_RX_STACK_SIZE=2048
CONFIG_BT_HCI_TX_STACK_SIZE_WITH_PROMPT=y
CONFIG_BT_HCI_TX_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_MAIN_STACK_SIZE=2400
CONFIG_IDLE_STACK_SIZE=128
CONFIG_ISR_STACK_SIZE=1024

CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_REBOOT=y
CONFIG_POWEROFF=y